const fs = require('fs');
const path = require('path');
const { 
  PROJECT_ID, 
  THEME_LAYOUT_TEMPLATE, 
  THEME_TWIKOO_TEMPLATE, 
  TWIKOO_ENV_PLACEHOLDER 
} = require('./config');
const { ensureDir, removeFileIfExists, toPosixPath } = require('./utils');

// 侧边栏链接构建
function buildSidebarLink(projectSourceDir, parentDir, fileName) {
  const relativeDir = path.relative(projectSourceDir, parentDir);
  const relativePrefix = relativeDir ? `${toPosixPath(relativeDir)}/` : '';
  return `/${relativePrefix}${fileName}`.replace(/\.md$/, '');
}

// 查找第一个侧边栏链接
function findFirstSidebarLink(items) {
  for (const item of items) {
    if (item.link) return item.link;
    if (item.items) {
      const nestedLink = findFirstSidebarLink(item.items);
      if (nestedLink) return nestedLink;
    }
  }
  return null;
}

// 生成菜单索引页
function generateMenuIndexContent(menuName, sidebarItems) {
  const firstLink = findFirstSidebarLink(sidebarItems);
  if (firstLink) {
    return `# ${menuName}\n\n[Start Reading](${firstLink})`;
  }
  return `# ${menuName}\n\nSelect a topic from the sidebar.`;
}

// 生成首页
function generateHomeContent(projectName, menus) {
  return `---
layout: home

hero:
  name: "${projectName}"
  text: "Documentation"
  tagline: "Generated by MDPress"
  actions:
    - theme: brand
      text: Get Started
      link: ${menus.length > 0 ? `/${menus[0].link}/` : `/`}

features:
  - title: Markdown Support
    details: Native Markdown support with extended features.
  - title: Vue-Powered
    details: Built with Vue 3 and VitePress.
---`;
}

// 生成VitePress配置
function generateVitePressConfig(projectName, navItems, sidebarMap, projectOutDir) {
  return `
import { defineConfig } from 'vitepress'

export default defineConfig({
  title: "${projectName}",
  description: "Documentation for ${projectName}",
  base: '/p/${PROJECT_ID}/',
  outDir: '${toPosixPath(projectOutDir)}',
  
  themeConfig: {
    nav: ${JSON.stringify(navItems, null, 2)},
    sidebar: ${JSON.stringify(sidebarMap, null, 2)},
    search: {
      provider: 'local'
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
    ]
  }
})
`;
}

// 主题文件生成
function createThemeLayoutContent() {
  const template = fs.readFileSync(THEME_LAYOUT_TEMPLATE, 'utf-8');
  return template.replace(TWIKOO_ENV_PLACEHOLDER, JSON.stringify(process.env.TWIKOO_ENV_ID || ''));
}

function createTwikooCommentsContent() {
  return fs.readFileSync(THEME_TWIKOO_TEMPLATE, 'utf-8');
}

function createThemeIndexContent(hasCustomTheme) {
  return `
import DefaultTheme from 'vitepress/theme'
import Layout from './Layout.vue'
${hasCustomTheme ? "import './custom.css'" : ""}

export default {
  extends: DefaultTheme,
  Layout: Layout
}
`;
}

// 设置主题
function setupTheme(themeName, vitepressDir, projectRoot) {
  const themeDir = path.join(vitepressDir, 'theme');
  ensureDir(themeDir);

  const themeSourcePath = path.join(projectRoot, 'public/theme', `${themeName}.css`);
  const themeDestPath = path.join(themeDir, 'custom.css');
  let hasCustomTheme = false;

  if (fs.existsSync(themeSourcePath)) {
    fs.copyFileSync(themeSourcePath, themeDestPath);
    hasCustomTheme = true;
    console.log(`Applied theme: ${themeName}`);
  } else {
    console.warn(`Theme CSS not found for: ${themeName}, using default.`);
  }

  fs.writeFileSync(path.join(themeDir, 'Layout.vue'), createThemeLayoutContent());
  fs.writeFileSync(path.join(themeDir, 'TwikooComments.vue'), createTwikooCommentsContent());
  fs.writeFileSync(path.join(themeDir, 'index.js'), createThemeIndexContent(hasCustomTheme));
}

// 写入VitePress配置
function writeVitePressConfig(projectName, nav, sidebar, vitepressDir, projectOutDir) {
  ensureDir(vitepressDir);
  removeFileIfExists(path.join(vitepressDir, 'config.js'));
  fs.writeFileSync(
    path.join(vitepressDir, 'config.mjs'),
    generateVitePressConfig(projectName, nav, sidebar, projectOutDir)
  );
}

module.exports = {
  buildSidebarLink,
  findFirstSidebarLink,
  generateMenuIndexContent,
  generateHomeContent,
  generateVitePressConfig,
  setupTheme,
  writeVitePressConfig
};
