const axios = require('axios');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const jwt = require('jsonwebtoken');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

// Constants
const BASE_URL = `http://localhost:${process.env.PORT || 3001}/api`;
const SECRET_KEY = process.env.SECRET_KEY || 'md-test-secret-key';
// Generate a system token for build process
const TOKEN = jwt.sign({ id: 1, email: 'system@build', name: 'System Build' }, SECRET_KEY, { expiresIn: '1h' });

let PROJECT_ID = process.env.PROJECT_ID; // Can be updated if not provided
const DOCS_ROOT = path.resolve(__dirname, '../docs');
let PROJECT_DOCS_DIR = path.join(DOCS_ROOT, PROJECT_ID || 'default');
const VITEPRESS_DIR = path.join(DOCS_ROOT, '.vitepress');
const REGISTRY_PATH = path.join(VITEPRESS_DIR, 'project-registry.json');

// --- Helpers ---

async function resolveProjectId() {
    if (PROJECT_ID) return;

    try {
        console.log('No PROJECT_ID provided. Attempting to find default project from database...');
        // Dynamically require prisma to avoid loading it if not needed (though here we need it)
        const prisma = require('../server/utils/prisma');
        const project = await prisma.projects.findFirst();
        
        if (project) {
            PROJECT_ID = project.id;
            console.log(`Using default project: ${project.name} (${PROJECT_ID})`);
            // Update dependent paths
            PROJECT_DOCS_DIR = path.join(DOCS_ROOT, PROJECT_ID);
        } else {
             console.error('No projects found in database. Please create a project first.');
             process.exit(1);
        }
    } catch (e) {
        console.error('Failed to resolve default project:', e.message);
        process.exit(1);
    }
}

function ensureDir(dir) {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

async function fetchApi(endpoint, params) {
    try {
        const res = await axios.get(`${BASE_URL}${endpoint}`, {
            params: { ...params, projectId: PROJECT_ID },
            headers: { token: TOKEN } 
        });
        return res.data.data;
    } catch (e) {
        console.error(`Failed to fetch ${endpoint}:`, e.message);
        return null;
    }
}

async function fetchProject() {
    const data = await fetchApi('/project/query', {});
    return data || { name: 'My Project' };
}

async function fetchMenus() {
    const data = await fetchApi('/menu/list', {});
    return data || [];
}

async function fetchSliders(link) {
    const data = await fetchApi('/slider/list', { link });
    return data || [];
}

async function fetchDoc(link, item, name) {
    const data = await fetchApi('/slider/item/list', { link, item, name });
    return data || "";
}

// --- Content Generation ---

async function processSliderItems(items, menuLink, parentDir) {
    const sidebarItems = [];
    
    for (const item of items) {
        // Sanitize name for file system
        const safeName = item.name.replace(/[\\/:*?"<>|]/g, '_').trim();
        if (!safeName) continue;

        if (item.group || (item.children && item.children.length > 0)) {
            // It's a group/folder
            const groupDir = path.join(parentDir, safeName);
            ensureDir(groupDir);
            
            const children = await processSliderItems(item.children || [], menuLink, groupDir);
            
            sidebarItems.push({
                text: item.name,
                collapsed: false,
                items: children
            });
        } else {
            // It's a file
            const fileName = `${safeName}.md`;
            const filePath = path.join(parentDir, fileName);
            
            const content = await fetchDoc(menuLink, item.link, item.name);
            fs.writeFileSync(filePath, content || '');
            
            // Calculate relative link for sidebar
            const relDir = path.relative(PROJECT_DOCS_DIR, parentDir);
            const urlPath = `/${PROJECT_ID}/` + (relDir ? relDir.split(path.sep).join('/') + '/' : '') + fileName; 
            const linkPath = urlPath.replace(/\.md$/, '');
            
            sidebarItems.push({
                text: item.name,
                link: linkPath
            });
        }
    }
    return sidebarItems;
}

function generateHomeContent(projectName, menus) {
    return `---
layout: home

hero:
  name: "${projectName}"
  text: "Documentation"
  tagline: "Generated by MDPress"
  actions:
    - theme: brand
      text: Get Started
      link: ${menus.length > 0 ? `/${PROJECT_ID}/${menus[0].link}/` : `/${PROJECT_ID}/`}

features:
  - title: Markdown Support
    details: Native Markdown support with extended features.
  - title: Vue-Powered
    details: Built with Vue 3 and VitePress.
---`;
}

function generateRootHomeContent(projectDataList) {
    let actionsYaml = '';
    for (const { id, name } of projectDataList) {
        actionsYaml += `    - theme: brand\n      text: ${name}\n      link: /${id}/\n`;
    }

    return `---
layout: home

hero:
  name: "MDPress Docs"
  text: "Select a Project"
  actions:
${actionsYaml}
---`;
}

function generateVitePressConfig(locales, globalSidebar) {
    return `
import { defineConfig } from 'vitepress'

export default defineConfig({
  // Global defaults
  title: "MDPress Docs",
  description: "Documentation Center",
  
  // Locales for project isolation
  locales: ${JSON.stringify(locales, null, 2)},
  
  themeConfig: {
    // Shared theme config if any (search, footer, etc.)
    search: {
      provider: 'local'
    },
    // Global Sidebar Configuration
    sidebar: ${JSON.stringify(globalSidebar, null, 2)}
  }
})
`;
}

// --- Registry Management ---

function loadRegistry() {
    ensureDir(VITEPRESS_DIR);
    if (fs.existsSync(REGISTRY_PATH)) {
        try {
            return JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf-8'));
        } catch (e) {
            console.error('Failed to parse registry, starting fresh.');
        }
    }
    return {};
}

function saveRegistry(registry) {
    ensureDir(VITEPRESS_DIR);
    fs.writeFileSync(REGISTRY_PATH, JSON.stringify(registry, null, 2));
}

// --- Main Workflow ---

async function cleanAndSetupDirs() {
    if (fs.existsSync(PROJECT_DOCS_DIR)) {
        try {
            fs.rmSync(PROJECT_DOCS_DIR, { recursive: true, force: true });
        } catch(e) {
            console.log('Warning: Could not clean project docs dir, proceeding...');
        }
    }
    ensureDir(PROJECT_DOCS_DIR);
}

async function processMenu(menu) {
    console.log(`Processing Menu: ${menu.name}`);
    
    const menuLink = menu.link;
    const menuDir = path.join(PROJECT_DOCS_DIR, menuLink);
    ensureDir(menuDir);

    const navItem = {
        text: menu.name,
        link: `/${PROJECT_ID}/${menuLink}/`, 
        activeMatch: `/${PROJECT_ID}/${menuLink}/`
    };

    const sliders = await fetchSliders(menuLink);
    const menuSidebarItems = await processSliderItems(sliders, menuLink, menuDir);
    
    // Create an index.md for the menu directory
    let indexContent = `# ${menu.name}\n\nSelect a topic from the sidebar.`;
    
    function findFirstLink(items) {
        for (const item of items) {
            if (item.link) return item.link;
            if (item.items) {
                const found = findFirstLink(item.items);
                if (found) return found;
            }
        }
        return null;
    }
    
    const firstLink = findFirstLink(menuSidebarItems);
    if (firstLink) {
            indexContent = `# ${menu.name}\n\n[Start Reading](${firstLink})`;
    }
    
    fs.writeFileSync(path.join(menuDir, 'index.md'), indexContent);

    return {
        navItem,
        sidebarKey: `/${PROJECT_ID}/${menuLink}/`,
        sidebarItems: menuSidebarItems
    };
}

async function main() {
    console.log('Starting local build...');
    
    await cleanAndSetupDirs();

    const project = await fetchProject();
    console.log(`Project: ${project.name}`);

    const menus = await fetchMenus();
    console.log(`Found ${menus.length} menus`);

    // Create Home Page in Project Dir
    fs.writeFileSync(path.join(PROJECT_DOCS_DIR, 'index.md'), generateHomeContent(project.name, menus));

    // Parallelize menu processing
    const results = await Promise.all(menus.map(menu => processMenu(menu)));

    const nav = [];
    const sidebar = {};

    results.forEach(res => {
        nav.push(res.navItem);
        sidebar[res.sidebarKey] = res.sidebarItems;
    });

    // Update Registry
    let registry = loadRegistry();
    registry[PROJECT_ID] = {
        name: project.name,
        nav: nav, 
        sidebar: sidebar
    };
    saveRegistry(registry);

    // Generate Config based on Registry
    let rootNav = [];
    const projectIds = Object.keys(registry);
    
    if (projectIds.length === 1) {
        rootNav = registry[projectIds[0]].nav;
    } else {
        rootNav = Object.entries(registry).map(([pId, pData]) => ({
            text: pData.name,
            link: `/${pId}/`
        }));
    }

    const locales = {
        root: {
            label: 'Home',
            lang: 'en',
            title: 'MDPress Docs',
            description: 'Documentation Center',
            themeConfig: {
                nav: rootNav,
                socialLinks: [
                    { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
                ]
            }
        }
    };
    
    let globalSidebar = {};
    const projectDataList = [];

    for (const [pId, pData] of Object.entries(registry)) {
        projectDataList.push({ id: pId, name: pData.name });

        locales[`/${pId}/`] = {
            label: pData.name,
            lang: 'en',
            title: pData.name,
            description: `Documentation for ${pData.name}`,
            themeConfig: {
                nav: pData.nav,
                // Sidebar is global now
                socialLinks: [
                    { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
                ]
            }
        };

        if (pData.sidebar) {
            for (const [key, items] of Object.entries(pData.sidebar)) {
                if (key.startsWith(`/${pId}/`)) {
                    globalSidebar[key] = items;
                } else {
                    const cleanKey = key.startsWith('/') ? key : '/' + key;
                    globalSidebar[`/${pId}${cleanKey}`] = items;
                }
            }
        }
    }

    // Write Config and Root Home
    // Ensure no conflicting config.js exists
    const oldConfigPath = path.join(VITEPRESS_DIR, 'config.js');
    if (fs.existsSync(oldConfigPath)) {
        fs.unlinkSync(oldConfigPath);
    }

    fs.writeFileSync(path.join(VITEPRESS_DIR, 'config.mjs'), generateVitePressConfig(locales, globalSidebar));
    fs.writeFileSync(path.join(DOCS_ROOT, 'index.md'), generateRootHomeContent(projectDataList));

    console.log('Data fetch complete. Building with VitePress...');
    
    try {
        execSync('npx vitepress build docs', { 
            stdio: 'inherit', 
            cwd: path.resolve(__dirname, '..') 
        });
        console.log('Build completed successfully!');
    } catch (e) {
        console.error('Build failed.');
        process.exit(1);
    }
}

main();
