const axios = require('axios');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Constants
const BASE_URL = 'https://mdpress.glicon.design/common';
const TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJVcmNNb0hKdnVsU09oaXI4ejctcyIsImlhdCI6MTc2OTA4MDA1OCwiZXhwIjoxNzcxNjcyMDU4fQ.vKgrQbI5mr9GSp41F6V2l5I6_4WCgBMfkXfOd7ZDyAw";
const PROJECT_ID = process.env.PROJECT_ID || "N-KUsUZgmt9J7JUcTITZd";

const DOCS_ROOT = path.resolve(__dirname, '../docs');
const PROJECT_DOCS_DIR = path.join(DOCS_ROOT, PROJECT_ID);

// Helper: Ensure directory exists
function ensureDir(dir) {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

// Helper: Fetch Project Info
async function fetchProject() {
    try {
        const res = await axios.get(`${BASE_URL}/project/query`, {
            params: { projectId: PROJECT_ID, token: TOKEN }
        });
        return res.data.data;
    } catch (e) {
        console.error('Failed to fetch project info:', e.message);
        return { name: 'My Project' };
    }
}

// Helper: Fetch Menus
async function fetchMenus() {
    try {
        const res = await axios.get(`${BASE_URL}/menu/list`, {
            params: { projectId: PROJECT_ID, token: TOKEN }
        });
        return res.data.data || [];
    } catch (e) {
        console.error('Failed to fetch menus:', e.message);
        return [];
    }
}

// Helper: Fetch Sliders for a Menu
async function fetchSliders(link) {
    try {
        const res = await axios.get(`${BASE_URL}/slider/list`, {
            params: { projectId: PROJECT_ID, token: TOKEN, link }
        });
        return res.data.data || [];
    } catch (e) {
        console.error(`Failed to fetch sliders for ${link}:`, e.message);
        return [];
    }
}

// Helper: Fetch Document Content
async function fetchDoc(link, item, name) {
    try {
        const res = await axios.get(`${BASE_URL}/slider/item/list`, {
            params: { projectId: PROJECT_ID, token: TOKEN, link, item, name }
        });
        return res.data.data || "";
    } catch (e) {
        console.error(`Failed to fetch doc content for ${name}:`, e.message);
        return "";
    }
}

// Recursive function to process slider items
async function processSliderItems(items, menuLink, parentDir) {
    const sidebarItems = [];
    
    for (const item of items) {
        // Sanitize name for file system
        const safeName = item.name.replace(/[\\/:*?"<>|]/g, '_').trim();
        if (!safeName) continue;

        if (item.group || (item.children && item.children.length > 0)) {
            // It's a group/folder
            const groupDir = path.join(parentDir, safeName);
            ensureDir(groupDir);
            
            const children = await processSliderItems(item.children || [], menuLink, groupDir);
            
            sidebarItems.push({
                text: item.name,
                collapsed: false,
                items: children
            });
        } else {
            // It's a file
            const fileName = `${safeName}.md`;
            const filePath = path.join(parentDir, fileName);
            
            // Check if file already exists (handle duplicate names in same folder?)
            // Overwrite is fine.
            
            const content = await fetchDoc(menuLink, item.link, item.name);
            fs.writeFileSync(filePath, content || '');
            
            // Calculate relative link for sidebar
            const relDir = path.relative(PROJECT_DOCS_DIR, parentDir);
            // Ensure path starts with /PROJECT_ID/
            const urlPath = `/${PROJECT_ID}/` + (relDir ? relDir.split(path.sep).join('/') + '/' : '') + fileName; 
            const linkPath = urlPath.replace(/\.md$/, '');
            
            sidebarItems.push({
                text: item.name,
                link: linkPath
            });
        }
    }
    return sidebarItems;
}

async function main() {
    console.log('Starting local build...');
    
    // Clean/Create project docs dir
    if (fs.existsSync(PROJECT_DOCS_DIR)) {
        try {
             fs.rmSync(PROJECT_DOCS_DIR, { recursive: true, force: true });
        } catch(e) {
             console.log('Warning: Could not clean project docs dir, proceeding...');
        }
    }
    ensureDir(PROJECT_DOCS_DIR);

    const project = await fetchProject();
    console.log(`Project: ${project.name}`);

    const menus = await fetchMenus();
    console.log(`Found ${menus.length} menus`);

    const nav = [];
    const sidebar = {};

    // Create Home Page in Project Dir
    const homeContent = `---
layout: home

hero:
  name: "${project.name}"
  text: "Documentation"
  tagline: "Generated by MDPress"
  actions:
    - theme: brand
      text: Get Started
      link: ${menus.length > 0 ? `/${PROJECT_ID}/${menus[0].link}/` : `/${PROJECT_ID}/`}

features:
  - title: Markdown Support
    details: Native Markdown support with extended features.
  - title: Vue-Powered
    details: Built with Vue 3 and VitePress.
---`;
    fs.writeFileSync(path.join(PROJECT_DOCS_DIR, 'index.md'), homeContent);

    // Create Root Home Page (Redirect or Link)
    const rootHomeContent = `---
layout: home

hero:
  name: "MDPress Docs"
  text: "Select a Project"
  actions:
    - theme: brand
      text: Go to ${project.name}
      link: /${PROJECT_ID}/
---`;
    fs.writeFileSync(path.join(DOCS_ROOT, 'index.md'), rootHomeContent);

    for (const menu of menus) {
        console.log(`Processing Menu: ${menu.name}`);
        
        const menuLink = menu.link;
        const menuDir = path.join(PROJECT_DOCS_DIR, menuLink);
        ensureDir(menuDir);

        // Add to Nav
        nav.push({
            text: menu.name,
            link: `/${PROJECT_ID}/${menuLink}/`, 
            activeMatch: `/${PROJECT_ID}/${menuLink}/`
        });

        const sliders = await fetchSliders(menuLink);
        const menuSidebarItems = await processSliderItems(sliders, menuLink, menuDir);
        
        // Use absolute path for sidebar key to support global sidebar configuration
        sidebar[`/${PROJECT_ID}/${menuLink}/`] = menuSidebarItems;

        // Create an index.md for the menu directory
        let indexContent = `# ${menu.name}\n\nSelect a topic from the sidebar.`;
        
        function findFirstLink(items) {
            for (const item of items) {
                if (item.link) return item.link;
                if (item.items) {
                    const found = findFirstLink(item.items);
                    if (found) return found;
                }
            }
            return null;
        }
        
        const firstLink = findFirstLink(menuSidebarItems);
        if (firstLink) {
             indexContent = `# ${menu.name}\n\n[Start Reading](${firstLink})`;
        }
        
        fs.writeFileSync(path.join(menuDir, 'index.md'), indexContent);
    }

    // Registry Handling
    const vitepressDir = path.join(DOCS_ROOT, '.vitepress');
    ensureDir(vitepressDir);
    const registryPath = path.join(vitepressDir, 'project-registry.json');
    let registry = {};
    if (fs.existsSync(registryPath)) {
        try {
            registry = JSON.parse(fs.readFileSync(registryPath, 'utf-8'));
        } catch (e) {
            console.error('Failed to parse registry, starting fresh.');
        }
    }

    // Update Registry with Current Project
    registry[PROJECT_ID] = {
        name: project.name,
        nav: nav, // Store the project's specific nav items
        sidebar: sidebar
    };
    fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2));

    // Construct Locales Config
    let rootNav = [];
    const projectIds = Object.keys(registry);
    
    if (projectIds.length === 1) {
        // Single Project: Flatten menu directly to Root
        rootNav = registry[projectIds[0]].nav;
    } else {
        // Multiple Projects: List projects as flat links (no dropdown)
        rootNav = Object.entries(registry).map(([pId, pData]) => ({
            text: pData.name,
            link: `/${pId}/`
        }));
    }

    const locales = {
        root: {
            label: 'Home',
            lang: 'en',
            title: 'MDPress Docs',
            description: 'Documentation Center',
            themeConfig: {
                nav: rootNav,
                socialLinks: [
                    { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
                ]
            }
        }
    };
    
    // Group Nav items by Project and Collect Global Sidebar
    let globalSidebar = {};
    for (const [pId, pData] of Object.entries(registry)) {
        locales[`/${pId}/`] = {
            label: pData.name,
            lang: 'en',
            title: pData.name,
            description: `Documentation for ${pData.name}`,
            themeConfig: {
                nav: pData.nav,
                // Sidebar removed from locale, moved to global
                socialLinks: [
                    { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
                ]
            }
        };

        // Merge sidebar into globalSidebar, ensuring keys are absolute
        if (pData.sidebar) {
            for (const [key, items] of Object.entries(pData.sidebar)) {
                // If key is already absolute (starts with /projectId/), use it
                if (key.startsWith(`/${pId}/`)) {
                    globalSidebar[key] = items;
                } else {
                    // Otherwise, prepend projectId (migration for old keys)
                    // Remove leading slash from key if present to avoid double slash, 
                    // but usually key is /KAISHI/, so we want /pId/KAISHI/
                    const cleanKey = key.startsWith('/') ? key : '/' + key;
                    globalSidebar[`/${pId}${cleanKey}`] = items;
                }
            }
        }
    }

    // Generate Config
    const configContent = `
import { defineConfig } from 'vitepress'

export default defineConfig({
  // Global defaults
  title: "MDPress Docs",
  description: "Documentation Center",
  
  // Locales for project isolation
  locales: ${JSON.stringify(locales, null, 2)},
  
  themeConfig: {
    // Shared theme config if any (search, footer, etc.)
    search: {
      provider: 'local'
    },
    // Global Sidebar Configuration
    sidebar: ${JSON.stringify(globalSidebar, null, 2)}
  }
})
`;
    
    fs.writeFileSync(path.join(vitepressDir, 'config.mjs'), configContent);

    // Update Root Home Page to list all projects
    let actionsYaml = '';
    for (const [pId, pData] of Object.entries(registry)) {
        actionsYaml += `    - theme: brand\n      text: ${pData.name}\n      link: /${pId}/\n`;
    }

    const realRootHomeContent = `---
layout: home

hero:
  name: "MDPress Docs"
  text: "Documentation Center"
  actions:
${actionsYaml}
---`;
    fs.writeFileSync(path.join(DOCS_ROOT, 'index.md'), realRootHomeContent);


    console.log('Data fetch complete. Building with VitePress...');
    
    try {
        execSync('npx vitepress build docs', { 
            stdio: 'inherit', 
            cwd: path.resolve(__dirname, '..') 
        });
        console.log('Build completed successfully!');
    } catch (e) {
        console.error('Build failed.');
        process.exit(1);
    }
}

main();
